-- 1. Garantir que BRUNO e NICOLLY existem como analistas
INSERT INTO analistas (nome, email, cargo) VALUES
  ('BRUNO', 'brunoaraujo.racontabilidade@gmail.com', 'analista'),
  ('NICOLLY', 'nicolly.racontabilidade@gmail.com', 'analista')
ON CONFLICT (email) DO NOTHING;

-- 2. Reatribuir empresas existentes ao analista correto
UPDATE empresas
SET analista_id = analistas.id
FROM analistas, (VALUES
  ('ALIANÇA BARREIRAS SERVIÇOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('ASI SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CASA DE SAUDE SAO JOAO LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CENTRO DE FISIOTERAPIA E ESPECIALIDADES LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CENTRO DE SAUDE VIDA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CENTRO MÉDICO ALIANÇA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CENTRO MÉDICO SÃO PAULO LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CLINICA OFTALMOLOGICA NARA PREIHS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('COTRIM FAVILA SERVIÇOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('D.S 13 SERVICOS DE SAUDE LTDA', 'ruan.racontabilidade@gmail.com'),
  ('DANTAS DE SA OFTALMOLOGIA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('GABA - ANESTESIOLOGISTAS DE BARREIRAS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('IMAGE RADIOLOGIA EIRELI', 'ruan.racontabilidade@gmail.com'),
  ('INSTITUTO DE SAUDE E TECNOLOGIA INTEGRADOS LTDA (CARLA SUELCK)', 'ruan.racontabilidade@gmail.com'),
  ('INSTITUTO LAVID DE MEDICINA INTEGRADA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('INSTITUTO MEDICO ESPECIALIZADO DE BARREIRAS S/S (IGOB)', 'ruan.racontabilidade@gmail.com'),
  ('IOB - INSTITUTO DE OLHOS DE BARREIRAS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('IUNES & GOBBI SERVICOS MEDICOS S/S', 'ruan.racontabilidade@gmail.com'),
  ('JM SORRISOS ODONTOLOGIA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('JULIA PEREIRA DOS SANTOS LTDA (LEM)', 'ruan.racontabilidade@gmail.com'),
  ('K&K FERNANDES SERVIÇOS MÉDICOS SS', 'ruan.racontabilidade@gmail.com'),
  ('LDO SERVICOS MEDICOS LTDA (LEM)', 'ruan.racontabilidade@gmail.com'),
  ('LUIZ CARLOS SERVICOS MEDICOS & CIA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('MED OESTE SERVIÇOS MEDICOS S/S', 'ruan.racontabilidade@gmail.com'),
  ('MLD SERMED LTDA', 'ruan.racontabilidade@gmail.com'),
  ('MLD SERMED LTDA (FILIAL MG)', 'ruan.racontabilidade@gmail.com'),
  ('OESTE MED MEDICINA DO TRABALHO LTDA (LEM)', 'ruan.racontabilidade@gmail.com'),
  ('ORTOCRED S/S', 'ruan.racontabilidade@gmail.com'),
  ('PREVLABOR SERVIÇOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('RIVELLI & LAMBOGLIA INSTITUTO CIRURGICO LTDA (GOIANIA)', 'ruan.racontabilidade@gmail.com'),
  ('SAOB - SERVICO DE ANESTESIA DO OESTE DA BAHIA S/S', 'ruan.racontabilidade@gmail.com'),
  ('SEMOG SERVICOS MEDICOS LTDA (PAULISTA)', 'ruan.racontabilidade@gmail.com'),
  ('THIAGO SALDANHA DE LUCENA SANDE VIEIRA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CMIND SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('GCAB CIRURGIA AVANCADA DE BARREIRAS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('JHDULIA ROBERTA CANCELIER SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('JHFP SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('JLA SERMED LTDA', 'ruan.racontabilidade@gmail.com'),
  ('MAYAN HAYRO SERVIÇOS MÉDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('OURO BRANCO MED LTDA', 'ruan.racontabilidade@gmail.com'),
  ('REIS & ANDRADE SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('RF ESTETICA AVANCADA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('RODRIGUES & BASTOS SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('ROSA BATISTA SERVIÇOS MÉDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('SAMUEL DIAS LEAL LTDA', 'ruan.racontabilidade@gmail.com'),
  ('SAUDE MENTAL INTEGRADA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('TATI PIRES SERMED LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CARVALHO & UEHARA SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('JACQUELINE PREIHS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('LUCAS BARRETO DA SILVA SERVICOS MEDICOS LTDA (SALVADOR)', 'ruan.racontabilidade@gmail.com'),
  ('MORGANA DOS PASSOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('ANA CAROLINA SANTOS GONCALVES SERVIÇOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CENTRO MEDICO VEREDA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('SERMED FALCAO FARIAS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('ALEX HENRIQUE SANTOS MENDES LTDA', 'ruan.racontabilidade@gmail.com'),
  ('ARAUJO NOGUEIRA SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('ASB SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('BEATRIZ ARAUJO ARSEGO LTDA', 'ruan.racontabilidade@gmail.com'),
  ('BEM ESTAR SERVICOS MEDICOS S/S LTDA', 'ruan.racontabilidade@gmail.com'),
  ('BRUNA SOUZA PSICOLOGIA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CAIO HENRIQUE RIOS BORDUQUE S/S LTDA (LEM)', 'ruan.racontabilidade@gmail.com'),
  ('CAMILLE LAVIGNE TAVARES S/S LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CAROLINE CARVALHO RODRIGUES SERVIÇOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CARVALHOMED S/S LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CASELLA NEVES & BORGES SERVIÇOS MEDICOS S/S', 'ruan.racontabilidade@gmail.com'),
  ('CENTRO DE DIAGNOSTICO DE APARELHO DIGESTIVO LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CMBS - CENTRO MEDICO BOA SORTE LTDA', 'ruan.racontabilidade@gmail.com'),
  ('D.S.S. SAÚDE SERVIÇOS MÉDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('DANAISY ESCOBAR FLEITES LTDA', 'ruan.racontabilidade@gmail.com'),
  ('DANIELA CARVALHO SERVICOS MEDICOS SS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('DENISE SANTANA OLIVEIRA EIRELI', 'ruan.racontabilidade@gmail.com'),
  ('DOREA & QUEIROZ SERVICOS MEDICOS S/S LTDA', 'ruan.racontabilidade@gmail.com'),
  ('DRA AMANDA BOMFIM SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('DRA LAYSSA FERNANDES SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('EMANUEL KIDS SERVIÇOS MÉDICOS S/S', 'ruan.racontabilidade@gmail.com'),
  ('ALINE BRASSANINI SCHULZ LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('ANGIOESTE CLINICA ESPECIALIZADA S/S LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('BRUNA GOMES ESTETICA AVANCADA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('CÂNDIDO & SANTOS LABORATÓRIO DE ANÁLISES CLÍNICAS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('CLINICA DUTTI - SAUDE DIGESTIVA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('CLÍNICA ODONTOLÓGICA DRA PATRICIA DIPP LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('COC MEDICINA AMBULATORIAL ORTOPEDICA DA COLUNA VERTEBRAL, OMBRO E COTOVELO LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('DR. ARTHUR BISINOTTO SERVIÇOS MÉDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('DR. JORGE GOMES SERVICOS MEDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('DR. JORGE GOMES SERVICOS MEDICOS LTDA FILIAL SEABRA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('DRA SASHA VILASBOAS SERVIÇOS MEDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('DUTTI MEDICINA E ODONTOLOGIA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('E.V.A ESPAÇO DE VIVÊNCIA ANESTÉSICA ODONTO & COLABORADORES LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('ELLO SERV LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('ELLO SERV LTDA FILIAL (BAIANÓPOLIS)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('ELLO SERV LTDA FILIAL (RODA VELHA - SD)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('EVANILDA RIBEIRO DE SANTANA ARAUJO & CIA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('FISIOPLAST CLINICA MEDICA S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('GURGEL & LOPES LTDA ( inativa)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('HAAVAH MED LTDA - baixada 12/2025 - prazo para Defis até 30/01/2026', 'brunoaraujo.racontabilidade@gmail.com'),
  ('HERCULES HIDEKI MAKIO SERVIÇOS MÉDICOS LTDA (LEM)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('IES-INSTITUTO ESPIRITO SANTO DE SAUDE S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA (BAIANÓPOLIS)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA (CÔCOS)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA (CRISTÓPOLIS)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA (INLAB+)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA (TABOCAS)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA FILIAL (ANGICAL)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA FILIAL (SANTA RITA)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA FILIAL (SANTANA)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA FILIAL (SÃO DESIDERIO)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA (RIACHÃO)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('IWASSE SERVICOS MEDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('JORGE GOMES OFTALMOLOGIA LTDA (FEIRA DE SANTANA)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('K.E.R. SAUDE LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('KENYA SATELES SERVICOS MEDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('LAR SAUDE S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('LLT SERVICOS MEDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('M.D SAUDE S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('MAPP FONOAUDIOLOGIA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('MEDPLESS ASSIST CLINICA MEDICA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('NEOVIDA SERVICO ESPECIALIZADO INFANTIL S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('OCCP - OESTE CIRURGIA DE CABEÇA E PESCOÇO LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('PRO SAUDE SERVIÇOS MÉDICOS EIRELI (FORMOSA)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('RIBEIRO & FARIAS SERVICOS MEDICOS S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('ROBERTA GARCIA DE LIMA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('ROCKENBACH SERVICOS MEDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('RW SERVICOS MEDICOS S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('SALUTE CUIDADO DOMICILIAR LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('T.R MELO SERVICOS MEDICOS EIRELI', 'brunoaraujo.racontabilidade@gmail.com'),
  ('T2L ALIANÇA INTEGRATIVA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('TAVARES & SANTOS SERVICOS MEDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('TEREZA CRISTINA MOREIRA GALVAO LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('VANESSA CRISTINE GURGEL DE MEDEIROS DIAS EIRELI', 'brunoaraujo.racontabilidade@gmail.com'),
  ('VICTOR DE SOUZA NASCIMENTO S/S LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('VITALCLIN MEDICINA E ODONTOLOGIA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('REIS E BARROS SERVIÇOS MEDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('XAVIER E BARROS SERVICOS MEDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('EMOCAO SUSTENTAVEL LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('F.R SERMED LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('FISTAROL MEDICINA E SAUDE LTDA (LEM)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('IB SERVIÇOS MÉDICOS S/S LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('IMAGEM X SERVICOS TECNICOS EM RADIOLOGIA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INTENSIPED LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('J. PINHEIRO SERVICOS MEDICOS S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('JUAN C V PALLITY', 'brunoaraujo.racontabilidade@gmail.com'),
  ('JULIANA CAROLINA DE CARVALHO BATISTA (CANÁPOLIS)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('JULIO CARLOS OLIVEIRA BATISTA JUNIOR', 'brunoaraujo.racontabilidade@gmail.com'),
  ('K&J SERVICOS MEDICOS S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('KATIA REJANE MARQUES BRITO LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('KELLEN KATHERINE ROCHA SANTOS S/S LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('KT SERVIÇOS MÉDICOS LTDA (LEM)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('LB MEDICINA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('LCSC MED SERVIÇOS MÉDICOS LTDA - LORENA (ANGICAL)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('LP MED LTDA (LEM)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('LUCAS GUIMARAES DE AZEVEDO LTDA (SP)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('M E F MATHEUS SERVICOS MEDICOS LTDA (LEM)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('MANOELLA PORTO CASTRO S/S LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('MARQUES & BARBOSA SERVIÇOS MÉDICOS S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('RESSONAR LAB VOZ E PERFOMANCE COMUNICATIVA (ACALENTO)', 'nicolly.racontabilidade@gmail.com'),
  ('ADF SAUDE LTDA (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('AGDA ROCHA ESTETICA AVANCADA LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('ALMEIDA BAOBÁ SERMED LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('AMANDA KELEN SERVICOS MEDICOS LTDA (MARANHÃO)', 'nicolly.racontabilidade@gmail.com'),
  ('AMANDA KIMURA SERVIÇOS MÉDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('ANA CAROLINA DA SILVA PEREIRA LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('ANA MARCIA ANDRADE SERVIÇOS MÉDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('ANDRADE MED LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('AVANCE FISIO LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('BRUNO MACEDO SERVIÇOS MÉDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('C.E.M.E SERVICOS MÉDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('C.S. DOS REIS LIMA LTDA (FORMOSA)', 'nicolly.racontabilidade@gmail.com'),
  ('CAIARA NUNES SERMED LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('CARLOS EDUARDO LINS FRANCA PIAU & CIA LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('CAROLINA HARUMI KURODA LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('CENTRO MÉDICO ADMINISTRATIVO LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('CLIMARI - CLINICA MEDICA MARIANA S/S', 'nicolly.racontabilidade@gmail.com'),
  ('CLINICA ALIAR LTDA (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('CLINICA CUIDAR CANAVIEIRAS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('CLINICA DE ODONTOLOGIA RENOVA SS', 'nicolly.racontabilidade@gmail.com'),
  ('CLINICA JULIANI LTDA (FILIAL) (TAGUATINGA)', 'nicolly.racontabilidade@gmail.com'),
  ('CLINICA JULIANI LTDA (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('CLINLAC - CLINICA E LABORATÓRIO DE ANÁLISE S/C LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('CML - CENTRO MEDICO LINDEMBERG LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('DAP CLINICA MEDICA LTDA (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('DRA. NAIRA SOUZA SERVIÇOS MÉDICOS LTDA - saída da contabilidade 09/2025', 'nicolly.racontabilidade@gmail.com'),
  ('E S SERVICOS MEDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('ENCOR SERVICOS MEDICOS S/S', 'nicolly.racontabilidade@gmail.com'),
  ('FALCON & ALMEIDA SOCIEDADE SIMPLES', 'nicolly.racontabilidade@gmail.com'),
  ('GOOB ORTOPEDISTAS DO OESTE DA BAHIA LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('GUADALUPE SERVICOS MEDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('HCB IMAGEM E DIAGNOSTICO LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('HOSPITAL SÃO FRANCISCO DE BARREIRAS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('IAP NEUMANN LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('IUB - INSTITUTO DE UROLOGIA DE BARREIRAS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('J L MEDICINA LTDA. (Brasília)', 'nicolly.racontabilidade@gmail.com'),
  ('KS MENDONCA SERVICOS MEDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('LABORATORIO PRO ANALISE LTDA FILIAL 03-43 (TAGUATINGA/TO)', 'nicolly.racontabilidade@gmail.com'),
  ('LABORATORIO PRO ANALISE LTDA FILIAL 02-62 (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('LABORATORIO PRO ANALISE LTDA FILIAL 04-24 (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('LABORATORIO PRO ANALISE LTDA FILIAL 05-05 (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('LABORATORIO PRO ANALISE LTDA MATRIZ (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('M. V. G. SILVA SERVICOS MEDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('NOVA VISTA SERVIÇOS MÉDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('OLIPE SERVICOS MEDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('R3 SERVICOS MEDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('RENATA LOPES VIEIRA & CIA LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('RIBEIRO & PERKUENY SERVICOS MEDICOS SS', 'nicolly.racontabilidade@gmail.com'),
  ('SARDA CARDENAS SERVICOS MEDICOS LTDA (SANTANA)', 'nicolly.racontabilidade@gmail.com'),
  ('SOMEB-SOCIEDADE MEDICA DE BARREIRAS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('T & E SERVICOS DE SAUDE LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('T & L EMPREENDIMENTOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('THALMA RIBEIRO MUNIZ S/S LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('THATIANE AZEVEDO SERVICOS MEDICOS LTDA (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('VITALLIE SERVICOS MEDICOS EIRELI (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('WMA SERVICOS DE SAUDE LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('FNA SERMED LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('ORTOPEDIA INTEGRADA - FELIPE SODRÉ SERMED LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('MEDMILY SERVIÇOS MÉDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('MILENA MARQUES MENDONCA S/S LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('MONIKE TAYNAN DE CARVALHO BARBOSA & CIA LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('MONTOLI SERVICOS MEDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('NEIVA BASTOS SERVICOS MEDICOS S/S', 'nicolly.racontabilidade@gmail.com'),
  ('NL SERVIÇOS MÉDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('NUNES MAIA SERVICOS MEDICOS LTDA (SP)', 'nicolly.racontabilidade@gmail.com'),
  ('ODONTOMENTORY LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('OLIVEIRA FRANCA SERVICOS MEDICOS LTDA (SÃO DESIDÉRIO)', 'nicolly.racontabilidade@gmail.com'),
  ('QUIRINO CAMPOS SERVICOS MEDICOS S/S LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('R. D. BARCELOS SERVICOS MEDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('RHES SERVICOS MEDICOS S/S', 'nicolly.racontabilidade@gmail.com'),
  ('RIBEIRO SANTO SERVIÇOS MÉDICOS EIRELI', 'nicolly.racontabilidade@gmail.com'),
  ('ROBERTO GUIMARAES REZENDE LTDA (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('SANTOS FRANCO SERVICOS MEDICOS S/S LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('SD SERVIÇOS DE SAÚDE SOCIEDADE SIMPLES', 'nicolly.racontabilidade@gmail.com'),
  ('SELENE SILVA MENDES S/S LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('SOGIB - SERVIÇO DE OBSTETRÍCIA E GINECOLOGIA S/S LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('THALES RODRIGUES DA SILVA LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('VALDIR CORTEZZI JUNIOR S/S LTDA (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('WRM SERMED LTDA', 'nicolly.racontabilidade@gmail.com')
) AS planilha(empresa_nome, analista_email)
WHERE empresas.nome = planilha.empresa_nome
  AND analistas.email = planilha.analista_email;

-- 3. Inserir empresas novas que ainda nao existem
INSERT INTO empresas (nome, analista_id, email_contato)
SELECT planilha.empresa_nome, analistas.id, NULL
FROM (VALUES
  ('ALIANÇA BARREIRAS SERVIÇOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('ASI SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CASA DE SAUDE SAO JOAO LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CENTRO DE FISIOTERAPIA E ESPECIALIDADES LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CENTRO DE SAUDE VIDA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CENTRO MÉDICO ALIANÇA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CENTRO MÉDICO SÃO PAULO LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CLINICA OFTALMOLOGICA NARA PREIHS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('COTRIM FAVILA SERVIÇOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('D.S 13 SERVICOS DE SAUDE LTDA', 'ruan.racontabilidade@gmail.com'),
  ('DANTAS DE SA OFTALMOLOGIA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('GABA - ANESTESIOLOGISTAS DE BARREIRAS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('IMAGE RADIOLOGIA EIRELI', 'ruan.racontabilidade@gmail.com'),
  ('INSTITUTO DE SAUDE E TECNOLOGIA INTEGRADOS LTDA (CARLA SUELCK)', 'ruan.racontabilidade@gmail.com'),
  ('INSTITUTO LAVID DE MEDICINA INTEGRADA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('INSTITUTO MEDICO ESPECIALIZADO DE BARREIRAS S/S (IGOB)', 'ruan.racontabilidade@gmail.com'),
  ('IOB - INSTITUTO DE OLHOS DE BARREIRAS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('IUNES & GOBBI SERVICOS MEDICOS S/S', 'ruan.racontabilidade@gmail.com'),
  ('JM SORRISOS ODONTOLOGIA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('JULIA PEREIRA DOS SANTOS LTDA (LEM)', 'ruan.racontabilidade@gmail.com'),
  ('K&K FERNANDES SERVIÇOS MÉDICOS SS', 'ruan.racontabilidade@gmail.com'),
  ('LDO SERVICOS MEDICOS LTDA (LEM)', 'ruan.racontabilidade@gmail.com'),
  ('LUIZ CARLOS SERVICOS MEDICOS & CIA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('MED OESTE SERVIÇOS MEDICOS S/S', 'ruan.racontabilidade@gmail.com'),
  ('MLD SERMED LTDA', 'ruan.racontabilidade@gmail.com'),
  ('MLD SERMED LTDA (FILIAL MG)', 'ruan.racontabilidade@gmail.com'),
  ('OESTE MED MEDICINA DO TRABALHO LTDA (LEM)', 'ruan.racontabilidade@gmail.com'),
  ('ORTOCRED S/S', 'ruan.racontabilidade@gmail.com'),
  ('PREVLABOR SERVIÇOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('RIVELLI & LAMBOGLIA INSTITUTO CIRURGICO LTDA (GOIANIA)', 'ruan.racontabilidade@gmail.com'),
  ('SAOB - SERVICO DE ANESTESIA DO OESTE DA BAHIA S/S', 'ruan.racontabilidade@gmail.com'),
  ('SEMOG SERVICOS MEDICOS LTDA (PAULISTA)', 'ruan.racontabilidade@gmail.com'),
  ('THIAGO SALDANHA DE LUCENA SANDE VIEIRA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CMIND SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('GCAB CIRURGIA AVANCADA DE BARREIRAS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('JHDULIA ROBERTA CANCELIER SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('JHFP SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('JLA SERMED LTDA', 'ruan.racontabilidade@gmail.com'),
  ('MAYAN HAYRO SERVIÇOS MÉDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('OURO BRANCO MED LTDA', 'ruan.racontabilidade@gmail.com'),
  ('REIS & ANDRADE SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('RF ESTETICA AVANCADA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('RODRIGUES & BASTOS SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('ROSA BATISTA SERVIÇOS MÉDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('SAMUEL DIAS LEAL LTDA', 'ruan.racontabilidade@gmail.com'),
  ('SAUDE MENTAL INTEGRADA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('TATI PIRES SERMED LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CARVALHO & UEHARA SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('JACQUELINE PREIHS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('LUCAS BARRETO DA SILVA SERVICOS MEDICOS LTDA (SALVADOR)', 'ruan.racontabilidade@gmail.com'),
  ('MORGANA DOS PASSOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('ANA CAROLINA SANTOS GONCALVES SERVIÇOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CENTRO MEDICO VEREDA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('SERMED FALCAO FARIAS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('ALEX HENRIQUE SANTOS MENDES LTDA', 'ruan.racontabilidade@gmail.com'),
  ('ARAUJO NOGUEIRA SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('ASB SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('BEATRIZ ARAUJO ARSEGO LTDA', 'ruan.racontabilidade@gmail.com'),
  ('BEM ESTAR SERVICOS MEDICOS S/S LTDA', 'ruan.racontabilidade@gmail.com'),
  ('BRUNA SOUZA PSICOLOGIA LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CAIO HENRIQUE RIOS BORDUQUE S/S LTDA (LEM)', 'ruan.racontabilidade@gmail.com'),
  ('CAMILLE LAVIGNE TAVARES S/S LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CAROLINE CARVALHO RODRIGUES SERVIÇOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CARVALHOMED S/S LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CASELLA NEVES & BORGES SERVIÇOS MEDICOS S/S', 'ruan.racontabilidade@gmail.com'),
  ('CENTRO DE DIAGNOSTICO DE APARELHO DIGESTIVO LTDA', 'ruan.racontabilidade@gmail.com'),
  ('CMBS - CENTRO MEDICO BOA SORTE LTDA', 'ruan.racontabilidade@gmail.com'),
  ('D.S.S. SAÚDE SERVIÇOS MÉDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('DANAISY ESCOBAR FLEITES LTDA', 'ruan.racontabilidade@gmail.com'),
  ('DANIELA CARVALHO SERVICOS MEDICOS SS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('DENISE SANTANA OLIVEIRA EIRELI', 'ruan.racontabilidade@gmail.com'),
  ('DOREA & QUEIROZ SERVICOS MEDICOS S/S LTDA', 'ruan.racontabilidade@gmail.com'),
  ('DRA AMANDA BOMFIM SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('DRA LAYSSA FERNANDES SERVICOS MEDICOS LTDA', 'ruan.racontabilidade@gmail.com'),
  ('EMANUEL KIDS SERVIÇOS MÉDICOS S/S', 'ruan.racontabilidade@gmail.com'),
  ('ALINE BRASSANINI SCHULZ LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('ANGIOESTE CLINICA ESPECIALIZADA S/S LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('BRUNA GOMES ESTETICA AVANCADA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('CÂNDIDO & SANTOS LABORATÓRIO DE ANÁLISES CLÍNICAS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('CLINICA DUTTI - SAUDE DIGESTIVA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('CLÍNICA ODONTOLÓGICA DRA PATRICIA DIPP LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('COC MEDICINA AMBULATORIAL ORTOPEDICA DA COLUNA VERTEBRAL, OMBRO E COTOVELO LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('DR. ARTHUR BISINOTTO SERVIÇOS MÉDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('DR. JORGE GOMES SERVICOS MEDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('DR. JORGE GOMES SERVICOS MEDICOS LTDA FILIAL SEABRA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('DRA SASHA VILASBOAS SERVIÇOS MEDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('DUTTI MEDICINA E ODONTOLOGIA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('E.V.A ESPAÇO DE VIVÊNCIA ANESTÉSICA ODONTO & COLABORADORES LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('ELLO SERV LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('ELLO SERV LTDA FILIAL (BAIANÓPOLIS)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('ELLO SERV LTDA FILIAL (RODA VELHA - SD)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('EVANILDA RIBEIRO DE SANTANA ARAUJO & CIA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('FISIOPLAST CLINICA MEDICA S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('GURGEL & LOPES LTDA ( inativa)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('HAAVAH MED LTDA - baixada 12/2025 - prazo para Defis até 30/01/2026', 'brunoaraujo.racontabilidade@gmail.com'),
  ('HERCULES HIDEKI MAKIO SERVIÇOS MÉDICOS LTDA (LEM)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('IES-INSTITUTO ESPIRITO SANTO DE SAUDE S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA (BAIANÓPOLIS)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA (CÔCOS)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA (CRISTÓPOLIS)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA (INLAB+)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA (TABOCAS)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA FILIAL (ANGICAL)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA FILIAL (SANTA RITA)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA FILIAL (SANTANA)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA FILIAL (SÃO DESIDERIO)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INLAB - CENTRO DE DIAGNOSTICO LABORATORIAL LTDA (RIACHÃO)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('IWASSE SERVICOS MEDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('JORGE GOMES OFTALMOLOGIA LTDA (FEIRA DE SANTANA)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('K.E.R. SAUDE LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('KENYA SATELES SERVICOS MEDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('LAR SAUDE S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('LLT SERVICOS MEDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('M.D SAUDE S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('MAPP FONOAUDIOLOGIA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('MEDPLESS ASSIST CLINICA MEDICA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('NEOVIDA SERVICO ESPECIALIZADO INFANTIL S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('OCCP - OESTE CIRURGIA DE CABEÇA E PESCOÇO LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('PRO SAUDE SERVIÇOS MÉDICOS EIRELI (FORMOSA)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('RIBEIRO & FARIAS SERVICOS MEDICOS S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('ROBERTA GARCIA DE LIMA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('ROCKENBACH SERVICOS MEDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('RW SERVICOS MEDICOS S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('SALUTE CUIDADO DOMICILIAR LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('T.R MELO SERVICOS MEDICOS EIRELI', 'brunoaraujo.racontabilidade@gmail.com'),
  ('T2L ALIANÇA INTEGRATIVA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('TAVARES & SANTOS SERVICOS MEDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('TEREZA CRISTINA MOREIRA GALVAO LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('VANESSA CRISTINE GURGEL DE MEDEIROS DIAS EIRELI', 'brunoaraujo.racontabilidade@gmail.com'),
  ('VICTOR DE SOUZA NASCIMENTO S/S LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('VITALCLIN MEDICINA E ODONTOLOGIA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('REIS E BARROS SERVIÇOS MEDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('XAVIER E BARROS SERVICOS MEDICOS LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('EMOCAO SUSTENTAVEL LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('F.R SERMED LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('FISTAROL MEDICINA E SAUDE LTDA (LEM)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('IB SERVIÇOS MÉDICOS S/S LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('IMAGEM X SERVICOS TECNICOS EM RADIOLOGIA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('INTENSIPED LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('J. PINHEIRO SERVICOS MEDICOS S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('JUAN C V PALLITY', 'brunoaraujo.racontabilidade@gmail.com'),
  ('JULIANA CAROLINA DE CARVALHO BATISTA (CANÁPOLIS)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('JULIO CARLOS OLIVEIRA BATISTA JUNIOR', 'brunoaraujo.racontabilidade@gmail.com'),
  ('K&J SERVICOS MEDICOS S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('KATIA REJANE MARQUES BRITO LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('KELLEN KATHERINE ROCHA SANTOS S/S LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('KT SERVIÇOS MÉDICOS LTDA (LEM)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('LB MEDICINA LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('LCSC MED SERVIÇOS MÉDICOS LTDA - LORENA (ANGICAL)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('LP MED LTDA (LEM)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('LUCAS GUIMARAES DE AZEVEDO LTDA (SP)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('M E F MATHEUS SERVICOS MEDICOS LTDA (LEM)', 'brunoaraujo.racontabilidade@gmail.com'),
  ('MANOELLA PORTO CASTRO S/S LTDA', 'brunoaraujo.racontabilidade@gmail.com'),
  ('MARQUES & BARBOSA SERVIÇOS MÉDICOS S/S', 'brunoaraujo.racontabilidade@gmail.com'),
  ('RESSONAR LAB VOZ E PERFOMANCE COMUNICATIVA (ACALENTO)', 'nicolly.racontabilidade@gmail.com'),
  ('ADF SAUDE LTDA (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('AGDA ROCHA ESTETICA AVANCADA LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('ALMEIDA BAOBÁ SERMED LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('AMANDA KELEN SERVICOS MEDICOS LTDA (MARANHÃO)', 'nicolly.racontabilidade@gmail.com'),
  ('AMANDA KIMURA SERVIÇOS MÉDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('ANA CAROLINA DA SILVA PEREIRA LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('ANA MARCIA ANDRADE SERVIÇOS MÉDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('ANDRADE MED LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('AVANCE FISIO LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('BRUNO MACEDO SERVIÇOS MÉDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('C.E.M.E SERVICOS MÉDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('C.S. DOS REIS LIMA LTDA (FORMOSA)', 'nicolly.racontabilidade@gmail.com'),
  ('CAIARA NUNES SERMED LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('CARLOS EDUARDO LINS FRANCA PIAU & CIA LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('CAROLINA HARUMI KURODA LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('CENTRO MÉDICO ADMINISTRATIVO LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('CLIMARI - CLINICA MEDICA MARIANA S/S', 'nicolly.racontabilidade@gmail.com'),
  ('CLINICA ALIAR LTDA (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('CLINICA CUIDAR CANAVIEIRAS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('CLINICA DE ODONTOLOGIA RENOVA SS', 'nicolly.racontabilidade@gmail.com'),
  ('CLINICA JULIANI LTDA (FILIAL) (TAGUATINGA)', 'nicolly.racontabilidade@gmail.com'),
  ('CLINICA JULIANI LTDA (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('CLINLAC - CLINICA E LABORATÓRIO DE ANÁLISE S/C LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('CML - CENTRO MEDICO LINDEMBERG LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('DAP CLINICA MEDICA LTDA (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('DRA. NAIRA SOUZA SERVIÇOS MÉDICOS LTDA - saída da contabilidade 09/2025', 'nicolly.racontabilidade@gmail.com'),
  ('E S SERVICOS MEDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('ENCOR SERVICOS MEDICOS S/S', 'nicolly.racontabilidade@gmail.com'),
  ('FALCON & ALMEIDA SOCIEDADE SIMPLES', 'nicolly.racontabilidade@gmail.com'),
  ('GOOB ORTOPEDISTAS DO OESTE DA BAHIA LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('GUADALUPE SERVICOS MEDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('HCB IMAGEM E DIAGNOSTICO LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('HOSPITAL SÃO FRANCISCO DE BARREIRAS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('IAP NEUMANN LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('IUB - INSTITUTO DE UROLOGIA DE BARREIRAS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('J L MEDICINA LTDA. (Brasília)', 'nicolly.racontabilidade@gmail.com'),
  ('KS MENDONCA SERVICOS MEDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('LABORATORIO PRO ANALISE LTDA FILIAL 03-43 (TAGUATINGA/TO)', 'nicolly.racontabilidade@gmail.com'),
  ('LABORATORIO PRO ANALISE LTDA FILIAL 02-62 (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('LABORATORIO PRO ANALISE LTDA FILIAL 04-24 (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('LABORATORIO PRO ANALISE LTDA FILIAL 05-05 (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('LABORATORIO PRO ANALISE LTDA MATRIZ (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('M. V. G. SILVA SERVICOS MEDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('NOVA VISTA SERVIÇOS MÉDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('OLIPE SERVICOS MEDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('R3 SERVICOS MEDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('RENATA LOPES VIEIRA & CIA LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('RIBEIRO & PERKUENY SERVICOS MEDICOS SS', 'nicolly.racontabilidade@gmail.com'),
  ('SARDA CARDENAS SERVICOS MEDICOS LTDA (SANTANA)', 'nicolly.racontabilidade@gmail.com'),
  ('SOMEB-SOCIEDADE MEDICA DE BARREIRAS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('T & E SERVICOS DE SAUDE LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('T & L EMPREENDIMENTOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('THALMA RIBEIRO MUNIZ S/S LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('THATIANE AZEVEDO SERVICOS MEDICOS LTDA (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('VITALLIE SERVICOS MEDICOS EIRELI (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('WMA SERVICOS DE SAUDE LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('FNA SERMED LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('ORTOPEDIA INTEGRADA - FELIPE SODRÉ SERMED LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('MEDMILY SERVIÇOS MÉDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('MILENA MARQUES MENDONCA S/S LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('MONIKE TAYNAN DE CARVALHO BARBOSA & CIA LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('MONTOLI SERVICOS MEDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('NEIVA BASTOS SERVICOS MEDICOS S/S', 'nicolly.racontabilidade@gmail.com'),
  ('NL SERVIÇOS MÉDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('NUNES MAIA SERVICOS MEDICOS LTDA (SP)', 'nicolly.racontabilidade@gmail.com'),
  ('ODONTOMENTORY LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('OLIVEIRA FRANCA SERVICOS MEDICOS LTDA (SÃO DESIDÉRIO)', 'nicolly.racontabilidade@gmail.com'),
  ('QUIRINO CAMPOS SERVICOS MEDICOS S/S LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('R. D. BARCELOS SERVICOS MEDICOS LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('RHES SERVICOS MEDICOS S/S', 'nicolly.racontabilidade@gmail.com'),
  ('RIBEIRO SANTO SERVIÇOS MÉDICOS EIRELI', 'nicolly.racontabilidade@gmail.com'),
  ('ROBERTO GUIMARAES REZENDE LTDA (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('SANTOS FRANCO SERVICOS MEDICOS S/S LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('SD SERVIÇOS DE SAÚDE SOCIEDADE SIMPLES', 'nicolly.racontabilidade@gmail.com'),
  ('SELENE SILVA MENDES S/S LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('SOGIB - SERVIÇO DE OBSTETRÍCIA E GINECOLOGIA S/S LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('THALES RODRIGUES DA SILVA LTDA', 'nicolly.racontabilidade@gmail.com'),
  ('VALDIR CORTEZZI JUNIOR S/S LTDA (LEM)', 'nicolly.racontabilidade@gmail.com'),
  ('WRM SERMED LTDA', 'nicolly.racontabilidade@gmail.com')
) AS planilha(empresa_nome, analista_email)
JOIN analistas ON analistas.email = planilha.analista_email
WHERE NOT EXISTS (
  SELECT 1 FROM empresas WHERE empresas.nome = planilha.empresa_nome
);

-- 4. Verificar resultado
SELECT a.nome AS analista, COUNT(e.id) AS total_empresas
FROM analistas a
LEFT JOIN empresas e ON e.analista_id = a.id
WHERE a.cargo = 'analista'
GROUP BY a.nome
ORDER BY a.nome;
